#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	
	//1. FILE pointer open & error handling
	if ((fp = fopen("schedule.dat", "r")) == NULL)
	{
		return -1;
	}
	
	//initializing the list
	printf("Reading the data files... \n");
	list = (void*)list_genList();
	
	int max = 50;
	char line[max];

	//2. read from the file
	while(!feof(fp)){
		fgets(line, max, fp);
		if(sscanf(line,"%s %s %d %d %d", name, place, &type, &month, &day)==5) // scanf로 변수를 잘 읽어온 경우에만 
		{
			//generate genSchedInfo structure by genSchedInfo function
			sched_genSchedInfo(name, place, type, month, day);
			//put the scheduling info instance generated by genSchedInfo function
			list_addTail(schedInfo, list);
		}
	}

	//close the file pointer
	fclose(fp);
	
	printf("Read done! %i schedules are read\n", list_len(list));
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		printf("\n");
		printf("1. print all the schedules\n");
		printf("2. search for schedules in the month\n");
		printf("3. search for schedules in the place\n");
		printf("4. search for specific type schedule\n");
		printf("5. exit\n\n");		
		
		//4. get option from keyboard
		printf(" select an option : ");
		scanf("%i", &option);
		
		switch(option)
		{
			case 1: //print all the schedules
				printf("printing all the schedules in the scheduler.....\n\n\n");
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//print count and each scheduling info element
					printf("--------------------------------------------------\n");
					sched_print(list);
					
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					//fill code this part - end
				}
				
				break;
				
			case 2: //search for schedules in the month
				printf("which month ? : ");
				scanf("%i", &month);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//print scheduling info elements matching to the month					
					printf("--------------------------------------------------\n");
					sched_getMonth(&month);
					sched_print(list);
					
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
					
				}
				
				break;
				
			case 3: //search for schedules in the place
				printf("which place ? : ");
				scanf("%s", place);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//print scheduling info elements matching to the place
					printf("--------------------------------------------------\n");
					sched_getPlace(&place);
					sched_print(list);
					
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 4: //search for specific type schedule
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", typeName);
				
				sched_convertType(typeName); //convert the name of the type into the enum(integer) value
				
				if (0 <= typeName < 7)
				{
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//print scheduling info elements matching to the place
						printf("--------------------------------------------------\n");
						sched_getType(&typeName);
						sched_print(list);
					
						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
						
						//fill code this part - end
						
					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5: //exit
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default: // 잘못된 입력  
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
	
	return 0;
}
